[package]
name = "disclose_bytes"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.32.0"

[dependencies]
disclose = { path = "../../../lib/disclose" }
utils = { path = "../../../lib/utils" }
subcircuits = { path = "../../../lib/subcircuits" }