[package]
name = "sig_check_id_data_rsa_pkcs_2048"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.36.0"

[dependencies]
sig_check_rsa = { path = "../../../../../../lib/sig-check/rsa" }
utils = { path = "../../../../../../lib/utils" }
commitment = { path = "../../../../../../lib/commitment/dsc-to-id" }
data_check_tbs_pubkey = { path = "../../../../../../lib/data-check/tbs-pubkey" }
