[package]
name = "data_check_integrity"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.22.0"

[dependencies]
data_check_integrity = { path = "../../../lib/data-check/integrity" }
data_check_expiry = { path = "../../../lib/data-check/expiry" }
commitment = { path = "../../../lib/commitment/integrity-to-disclosure" }
