[package]
name = "sig_check_id_data_ecdsa_nist_p521"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.36.0"

[dependencies]
sig_check_ecdsa = { path = "../../../../../../lib/sig-check/ecdsa" }
commitment = { path = "../../../../../../lib/commitment/dsc-to-id" }
data_check_tbs_pubkey = { path = "../../../../../../lib/data-check/tbs-pubkey" }
utils = { path = "../../../../../../lib/utils" }
