[package]
name = "data_check_expiry"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.22.0"

[dependencies]
data_check_expiry = { path = "../../../lib/data-check/expiry" }
utils = { path = "../../../lib/utils" }