[package]
name = "sig_check_id_data_ecdsa_nist_p256"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.36.0"

[dependencies]
sig_check_ecdsa = { path = "../../../../../../lib/sig-check/ecdsa/nist/p256" }
utils = { path = "../../../../../../lib/utils" }
subcircuits = { path = "../../../../../../lib/subcircuits" }
